# Generated by Django 4.2 on 2025-07-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='item_image',
        ),
    ]
